version: "3"

services:
  web:
    build: ./client
    container_name: web_app
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    restart: always
    ports:
      - 3000:3000

  api:
    build: ./backend
    container_name: api_app
    restart: always
    ports:
      - 3333:3333
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  nodemodules: {}
